baseURL = 'http://AdriansHall.github.io'
languageCode = 'en-gb'
title = 'Adrians Hall'
theme = 'aafu'
publishDir = 'docs'

[params]
    title = "Adrian's Hall"
    author = "Adrian de Lima"
    description = "Adrian's Hall"
    copyright = "rights reserved"

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "dark"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = false
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Adrian de Lima"
        tagline = "Violinist, Composer"
        location = ""
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/adrian-de-lima"
            title = "LinkedIn"		

        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/AdriandeLima"
            title = "GitHub"

        [[params.social.list]]
            icon = "fab fa-youtube"
            url = "https://www.youtube.com/@AdriandeLima/videos"
            title = "Youtube"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    #[[params.showInAccordion]]
        #item = "publication"
    #[[params.showInAccordion]]
     #   item = "project"
    #[[params.showInAccordion]]
     #   item = "skill"
    #[[params.showInAccordion]]
     #   item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "I am a musician specializing in performance, composition and music technology. Music has been a big part of my life for as long as I can remember. I was fortunate enough to have parents brave enough to sacrifice their time, money (and ears) in order for me to be heavily involved in music making throughout my childhood, and this naturally blossomed into a pursuit of my passion at UoB. My journey into music technology began during a stint as a performing arts technician. I quickly learned that there’s more to a microphone than just plugging it in, and that sparked an ongoing fascination with sound design and recording. Since then, I’ve been mixing, composing, and experimenting with tech to bring my ideas to life. What really drives me, though, is sharing my music with others, and providing the means for music to inspire them. There's something incredibly rewarding about supporting others in pursuing their passions, whether it's through collaboration, mentorship, or just sharing knowledge along the way."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Performing Arts Technician"
            dates = "2021 - 2022"
            company = "The Blue School, Wells"
            details = "The responsibility of a wide range of tasks fall to a secondary school performing arts technician. These include inventory management and equipment maintenance, audio and video production, live sound and lighting for performances, lesson and tech support, school club management, and inter-departmental communication for both the music and drama departments."

        [[params.experience.list]]
            position = "Orchestral Musician"
            dates = "2022-2025"
            company = "University of Birmingham"
            details = "Played in 4 orchestras, including leading, as principal violinist in the Blue School's orchestra and string orchestra for 4 years, and the University of Birmingham string orchestra for a year. Participated in the University of Birmingham’s Music Society, playing in the string orchestra, the university’s Philharmonic orchestra, a piano trio and a string quartet."

        [[params.experience.list]]
            position = "Music Manager"
            dates = "2022-2023"
            company = "University of Birmingham"
            details = "Acted as Chamber-Music-Network manager in the University of Birmingham Music Society, organising a social each term to facilitate the formation of chamber-music groups and keeping a detailed register and mailing list while organising performance sessions for the groups."

        [[params.experience.list]]
            position = "Music Teacher"
            dates = "2020-2021"
            company = "Independent"
            details = "Taught beginner students violin and piano, teaching both technique and music theory and providing feedback from week to week."

          [[params.experience.list]]
            position = "Recording Engineer"
            dates = "Present"
            company = "Independent"
            details = "Engineered multiple recording projects and concerts, enhancing technical skills in live audio mixing, Reaper and Logic Pro DAWs, and video editing using Final Cut Pro."

          
    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Bachelor's in Music"
            college = "University of Birmingham"
            dates = "2022 - 2025"
            # thesis_title = "Eff"
            # thesis_url = "#"
        [[params.education.list]]
            degree = "ATCL in Piano performance"
            college = "Trinity College London"
            dates = "2019"

        [[params.education.list]]
            degree = "ARSM in Violin performance"
            college = "Associated Board of the Royal Schools of Music"
            dates = "2018"

        [[params.education.list]]
            degree = "Grade 5 Music Theory"
            college = "Associated Board of the Royal Schools of Music"
            dates = "2014"    

        [[params.education.list]]
            degree = "Grade 8 Violin"
            college = "Associated Board of the Royal Schools of Music"
            dates = "2016"

        [[params.education.list]]
            degree = "Grade 8 Piano"
            college = "Trinity College London"
            dates = "2017"

        [[params.education.list]]
            degree = "A levels"
            thesis_title = "Music, Physics, Mathematics"
            college = "The Blue School, Wells"
            dates = "2018 - 2020"


    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        #The order below determines the order in which the items appear in "Publications" section
        format = ["date", "authors", "title", "journal"]
        #If you don't want to group publications, comment the line below by adding # at the beginning
        types = ["Journal Articles", "Proceedings"]

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Journal Articles"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Journal Articles"
		
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            url = "#"
            type = "Proceedings"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "Project 1"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 2"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 3"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "Project 4"
            url = "#"
            description = "Description of the project"

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Skill 1, Skill 2"
            skillrating = 90
        [[params.skill.list]]
            skill = "Skill 3"
            skillrating = 80
        [[params.skill.list]]
            skill = "Skill 4"
            skillrating = 50

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]
            hobby = "Cooking"
        [[params.hobby.list]]
            hobby = "Hiking"
        [[params.hobby.list]]
            hobby = "Baking"
